/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.practica5.vista;

import ec.edu.ups.practica5.vista.compositor.VentanaAgregarCantante;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private VentanaAgregarCantante ventanaAgregarCantante;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuCompositor = new javax.swing.JMenu();
        MenuAgregarCompositor = new javax.swing.JMenuItem();
        MenuBuscarCompositor = new javax.swing.JMenuItem();
        MenuActualizarCompositor = new javax.swing.JMenuItem();
        MenuEliminarCompositor = new javax.swing.JMenuItem();
        MenuListarCompositor = new javax.swing.JMenuItem();
        MenuCantante = new javax.swing.JMenu();
        MenuAgregarCantante = new javax.swing.JMenuItem();
        MenuBuscarCantante = new javax.swing.JMenuItem();
        MenuActualizarCantante = new javax.swing.JMenuItem();
        MenuEliminarCantante = new javax.swing.JMenuItem();
        MenuListarCantante = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        MenuCompositor.setText("Compositor");

        MenuAgregarCompositor.setText("Agregar");
        MenuAgregarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAgregarCompositorActionPerformed(evt);
            }
        });
        MenuCompositor.add(MenuAgregarCompositor);

        MenuBuscarCompositor.setText("Buscar");
        MenuCompositor.add(MenuBuscarCompositor);

        MenuActualizarCompositor.setText("Actualizar");
        MenuCompositor.add(MenuActualizarCompositor);

        MenuEliminarCompositor.setText("Eliminar");
        MenuCompositor.add(MenuEliminarCompositor);

        MenuListarCompositor.setText("Listar");
        MenuListarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListarCompositorActionPerformed(evt);
            }
        });
        MenuCompositor.add(MenuListarCompositor);

        jMenuBar2.add(MenuCompositor);

        MenuCantante.setText("Cantante");

        MenuAgregarCantante.setText("Agregar");
        MenuCantante.add(MenuAgregarCantante);

        MenuBuscarCantante.setText("Buscar");
        MenuCantante.add(MenuBuscarCantante);

        MenuActualizarCantante.setText("Actualizar");
        MenuCantante.add(MenuActualizarCantante);

        MenuEliminarCantante.setText("Eliminar");
        MenuCantante.add(MenuEliminarCantante);

        MenuListarCantante.setText("Listar");
        MenuListarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListarCantanteActionPerformed(evt);
            }
        });
        MenuCantante.add(MenuListarCantante);

        jMenuBar2.add(MenuCantante);

        jMenu1.setText("Cliente");
        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuListarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListarCompositorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuListarCompositorActionPerformed

    private void MenuListarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListarCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuListarCantanteActionPerformed

    private void MenuAgregarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgregarCompositorActionPerformed
        // TODO add your handling code here:
        if(ventanaAgregarCantante == null){
            ventanaAgregarCantante = new VentanaAgregarCantante();
            
        }
    }//GEN-LAST:event_MenuAgregarCompositorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuActualizarCantante;
    private javax.swing.JMenuItem MenuActualizarCompositor;
    private javax.swing.JMenuItem MenuAgregarCantante;
    private javax.swing.JMenuItem MenuAgregarCompositor;
    private javax.swing.JMenuItem MenuBuscarCantante;
    private javax.swing.JMenuItem MenuBuscarCompositor;
    private javax.swing.JMenu MenuCantante;
    private javax.swing.JMenu MenuCompositor;
    private javax.swing.JMenuItem MenuEliminarCantante;
    private javax.swing.JMenuItem MenuEliminarCompositor;
    private javax.swing.JMenuItem MenuListarCantante;
    private javax.swing.JMenuItem MenuListarCompositor;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
