/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica5.vista.cantante;

import ec.edu.ups.practica5.controlador.ControladorCantante;
import ec.edu.ups.practica5.modelo.Cantante;
import ec.edu.ups.practica5.modelo.Compositor;
import ec.edu.ups.practica5.modelo.Disco;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class VentanaActualizarCantante extends javax.swing.JInternalFrame {

    private ControladorCantante controladorCantante;
    private List<Disco> listaDiscos;
    private ResourceBundle mensajes;

    /**
     * /**
     * Creates new form VentanaActualizarCantante
     */
    public VentanaActualizarCantante(ControladorCantante controladorCantante) {
        initComponents();

    }

    public void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jlCodigo.setText(mensajes.getString("txtCodigo"));
        jlNombre.setText(mensajes.getString("txtNombre"));
        jlApellido.setText(mensajes.getString("txtApellido"));
        jlEdad.setText(mensajes.getString("txtEdad"));
        jlNacionalidad.setText(mensajes.getString("cbxNacionalidad"));
        jlSalario.setText(mensajes.getString("txtSalario"));
        jlSalario1.setText(mensajes.getString("txtNombreArtisticoC"));
        jlSalario2.setText(mensajes.getString("radioButtonRock"));
        jlSalario3.setText(mensajes.getString("txtSencillosC"));
        jlSalario4.setText(mensajes.getString("txtConciertosC"));
        jlSalario5.setText(mensajes.getString("txtGirasC"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jlCodigo = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlEdad = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNacionalidad = new javax.swing.JLabel();
        jlSalario = new javax.swing.JLabel();
        jlSalario1 = new javax.swing.JLabel();
        jlSalario2 = new javax.swing.JLabel();
        jlSalario3 = new javax.swing.JLabel();
        jlSalario4 = new javax.swing.JLabel();
        jlSalario5 = new javax.swing.JLabel();
        txtCodigoC = new javax.swing.JTextField();
        txtNombreC = new javax.swing.JTextField();
        txtApellidoC = new javax.swing.JTextField();
        txtEdadC = new javax.swing.JTextField();
        txtSalarioC = new javax.swing.JTextField();
        txtNombreArtisticoC = new javax.swing.JTextField();
        txtSencillosC = new javax.swing.JTextField();
        txtConciertosC = new javax.swing.JTextField();
        txtGirasC = new javax.swing.JTextField();
        cbxnacionalidadC = new javax.swing.JComboBox<>();
        radioButtonRock = new javax.swing.JRadioButton();
        radioButtonPop = new javax.swing.JRadioButton();
        radioButtonHiphop = new javax.swing.JRadioButton();
        radioButtonRap = new javax.swing.JRadioButton();
        radioButtonHeavyMetal = new javax.swing.JRadioButton();
        radioButtonReggae = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actualizar Cantante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jlCodigo.setText("Código");

        jlNombre.setText("Nombre");

        jlEdad.setText("Edad");

        jlApellido.setText("Apellido");

        jlNacionalidad.setText("Nacionalidad");

        jlSalario.setText("Salario");

        jlSalario1.setText("Nombre Artístico");

        jlSalario2.setText("Genero Musical");

        jlSalario3.setText("Número de sencillos");

        jlSalario4.setText("Número de conciertos");

        jlSalario5.setText("Número de giras");

        txtCodigoC.setToolTipText("Ingrese las cancionesTop100Billboard");
        txtCodigoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCActionPerformed(evt);
            }
        });

        txtNombreC.setToolTipText("Ingrese las cancionesTop100Billboard");
        txtNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCActionPerformed(evt);
            }
        });

        txtApellidoC.setToolTipText("Ingrese las cancionesTop100Billboard");
        txtApellidoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCActionPerformed(evt);
            }
        });

        txtEdadC.setToolTipText("Ingrese las cancionesTop100Billboard");
        txtEdadC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadCActionPerformed(evt);
            }
        });

        txtSalarioC.setToolTipText("Ingrese las cancionesTop100Billboard");
        txtSalarioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioCActionPerformed(evt);
            }
        });

        txtNombreArtisticoC.setToolTipText("Ingrese las cancionesTop100Billboard");
        txtNombreArtisticoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreArtisticoCActionPerformed(evt);
            }
        });

        txtSencillosC.setToolTipText("Ingrese las cancionesTop100Billboard");
        txtSencillosC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSencillosCActionPerformed(evt);
            }
        });

        txtConciertosC.setToolTipText("Ingrese las cancionesTop100Billboard");
        txtConciertosC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConciertosCActionPerformed(evt);
            }
        });

        txtGirasC.setToolTipText("Ingrese las cancionesTop100Billboard");
        txtGirasC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGirasCActionPerformed(evt);
            }
        });

        cbxnacionalidadC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Inglesa", "Colombiana", "Cubana ", "Chilena", "Ecuatoriana", "Mexicana", "Peruana", "Americana", "Española" }));

        radioButtonRock.setSelected(true);
        radioButtonRock.setText("Rock");

        radioButtonPop.setText("Pop");

        radioButtonHiphop.setText("Hiphop");

        radioButtonRap.setText("Rap");

        radioButtonHeavyMetal.setText("Heavy Metal");

        radioButtonReggae.setText("Reggae");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodigo)
                            .addComponent(jlNombre)
                            .addComponent(jlApellido)
                            .addComponent(jlEdad)
                            .addComponent(jlNacionalidad)
                            .addComponent(jlSalario)
                            .addComponent(jlSalario1)
                            .addComponent(jlSalario2)
                            .addComponent(jlSalario3)
                            .addComponent(jlSalario4)
                            .addComponent(jlSalario5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGirasC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConciertosC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSencillosC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreArtisticoC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalarioC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdadC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxnacionalidadC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(radioButtonRock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonPop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonHiphop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonRap)
                                .addGap(18, 18, 18)
                                .addComponent(radioButtonHeavyMetal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioButtonReggae)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdadC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSalarioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreArtisticoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cbxnacionalidadC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlSalario2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioButtonPop)
                        .addComponent(radioButtonHiphop)
                        .addComponent(radioButtonRap)
                        .addComponent(radioButtonHeavyMetal)
                        .addComponent(radioButtonRock)
                        .addComponent(radioButtonReggae)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSalario3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSencillosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSalario4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConciertosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSalario5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGirasC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtCodigoC.setText("");
        this.setVisible(false);
        btnActualizar.setEnabled(false);
        this.limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCodigoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCActionPerformed

    private void txtNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCActionPerformed

    private void txtApellidoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCActionPerformed

    private void txtEdadCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadCActionPerformed

    private void txtSalarioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioCActionPerformed

    private void txtNombreArtisticoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreArtisticoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreArtisticoCActionPerformed

    private void txtSencillosCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSencillosCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSencillosCActionPerformed

    private void txtConciertosCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConciertosCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConciertosCActionPerformed

    private void txtGirasCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGirasCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGirasCActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int codigo = Integer.parseInt(txtCodigoC.getText());
        Cantante cantante = controladorCantante.buscarCantante(codigo);
        if (cantante != null) {
            txtNombreC.setText(cantante.getNombre());
            txtApellidoC.setText(cantante.getApellido());
            txtEdadC.setText(Integer.toString(cantante.getEdad()));
            cbxnacionalidadC.setSelectedItem(cantante.getNacionalidad());
            txtSalarioC.setText(Double.toString(cantante.getSalario()));
            txtNombreArtisticoC.setText(cantante.getNombreArtistico());
            radioButtonRock.setText(cantante.getGeneroMusical());
            txtSencillosC.setText(Integer.toString(cantante.getNumeroDeSencillos()));
            txtConciertosC.setText(Integer.toString(cantante.getNumeroDeConciertos()));
            txtGirasC.setText(Integer.toString(cantante.getNumeroDeGiras()));
        } else {
            JOptionPane.showMessageDialog(this, "La persona con codigo " + codigo + " no ha sido encontrada!");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            int codigo = 0;
            if (!txtCodigoC.getText().isEmpty()) {
                codigo = Integer.parseInt(txtCodigoC.getText());
            } else {
                throw new IllegalArgumentException("El campo Código no puede estar vacío.");
            }

            String nombre = txtNombreC.getText();
            String apellido = txtApellidoC.getText();

            int edad = 0;
            if (!txtEdadC.getText().isEmpty()) {
                edad = Integer.parseInt(txtEdadC.getText());
            } else {
                throw new IllegalArgumentException("El campo Edad no puede estar vacío.");
            }

            String nacionalidad = cbxnacionalidadC.getSelectedItem().toString();

            double salario = 0.0;
            if (!txtSalarioC.getText().isEmpty()) {
                salario = Double.parseDouble(txtSalarioC.getText());
            } else {
                throw new IllegalArgumentException("El campo Salario no puede estar vacío.");
            }

            String nombreArtistico = txtNombreArtisticoC.getText();
            String generoMusical = radioButtonRock.getText();

            int numeroDeSencillos = 0;
            if (!txtSencillosC.getText().isEmpty()) {
                numeroDeSencillos = Integer.parseInt(txtSencillosC.getText());
            } else {
                throw new IllegalArgumentException("El campo Número de Sencillos no puede estar vacío.");
            }

            int numeroDeConciertos = 0;
            if (!txtConciertosC.getText().isEmpty()) {
                numeroDeConciertos = Integer.parseInt(txtConciertosC.getText());
            } else {
                throw new IllegalArgumentException("El campo Número de Conciertos no puede estar vacío.");
            }

            int numeroDeGiras = 0;
            if (!txtGirasC.getText().isEmpty()) {
                numeroDeGiras = Integer.parseInt(txtGirasC.getText());
            } else {
                throw new IllegalArgumentException("El campo Número de Giras no puede estar vacío.");
            }

            if (nombre.length() > 25 || apellido.length() > 25 || nacionalidad.length() > 25) {
                JOptionPane.showMessageDialog(this, "El nombre, apellido o nacionalidad es muy largo, debe ser menor a 25 caracteres.");
            } else {
                Cantante cantante = new Cantante(nombreArtistico, generoMusical, numeroDeSencillos, numeroDeConciertos, numeroDeGiras, codigo, nombre, apellido, edad, nacionalidad, salario);
                String ruta = null;
                controladorCantante.crearCantante(cantante, ruta);
                JOptionPane.showMessageDialog(this, "Compositor agregado exitosamente.");
                limpiarCampos();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: uno o más campos no son numéricos.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed
    public void limpiarCampos() {
        this.txtCodigoC.setText("");
        this.txtNombreArtisticoC.setText("");
        this.txtApellidoC.setText("");
        this.txtEdadC.setText("");
        this.txtSalarioC.setText("");
        this.txtNombreArtisticoC.setText("");
        this.txtSencillosC.setText("");
        this.txtConciertosC.setText("");
        this.txtGirasC.setText("");
        this.radioButtonRock.setSelected(true);
    }

    private void cambiarEstadoCampos(boolean estado) {
        this.txtCodigoC.setEnabled(!estado);
        this.txtNombreArtisticoC.setEnabled(estado);
        this.txtApellidoC.setEnabled(estado);
        this.txtEdadC.setEnabled(estado);
        this.cbxnacionalidadC.setEnabled(estado);
        this.txtSalarioC.setEnabled(estado);
        this.radioButtonRock.setEnabled(estado);
        this.txtSencillosC.setEnabled(estado);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbxnacionalidadC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlEdad;
    private javax.swing.JLabel jlNacionalidad;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlSalario;
    private javax.swing.JLabel jlSalario1;
    private javax.swing.JLabel jlSalario2;
    private javax.swing.JLabel jlSalario3;
    private javax.swing.JLabel jlSalario4;
    private javax.swing.JLabel jlSalario5;
    private javax.swing.JRadioButton radioButtonHeavyMetal;
    private javax.swing.JRadioButton radioButtonHiphop;
    private javax.swing.JRadioButton radioButtonPop;
    private javax.swing.JRadioButton radioButtonRap;
    private javax.swing.JRadioButton radioButtonReggae;
    private javax.swing.JRadioButton radioButtonRock;
    private javax.swing.JTextField txtApellidoC;
    private javax.swing.JTextField txtCodigoC;
    private javax.swing.JTextField txtConciertosC;
    private javax.swing.JTextField txtEdadC;
    private javax.swing.JTextField txtGirasC;
    private javax.swing.JTextField txtNombreArtisticoC;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtSalarioC;
    private javax.swing.JTextField txtSencillosC;
    // End of variables declaration//GEN-END:variables
}
